### ISSUE TITLE
Create endpoints to allow users to update their profile information and passwords.

### ISSUE THREAD

**Issue by jean-michelet** [fastify/demo#36]

**Comment by Mathieuka** [comment]
Hello @jean-michelet if it is available, can you assign it to me ?

Thx

**Comment by jean-michelet** [comment]
Go ahead!

**Comment by Mathieuka** [comment]
For the password update scenario, prior authentication is logically required. 

Currently, passwords in the database are stored in plain text via seeding. 

For authentication, we apply a hashing function to the plain text password, which means it is impossible to correctly compare the password entered by the user.

```
const user = ... // user from db

// user.password is an plain text password and i think fastify.compare applies a hash function to it
const isPasswordValid = await fastify.compare(password, user.password)
```

Before the implementation of the update endpoint, I propose, in the same pull request, to modify the seeding to store passwords in a hashed format rather than in plain text to resolve this issue. 

We can also include demonstration passwords in the documentation.

Did I miss anything?

**Comment by jean-michelet** [comment]
> Currently, passwords in the database are stored in plain text via seeding.

No, we use a [`scriptHash`](https://github.com/fastify/demo/blob/main/src/plugins/custom/scrypt.ts) function:
https://github.com/fastify/demo/blob/9455f5c2684403b70e209be6f1dfe48cb508c625/scripts/seed-database.ts#L51

**Comment by Mathieuka** [comment]
> > Currently, passwords in the database are stored in plain text via seeding.
> 
> No, we use a [`scriptHash`](https://github.com/fastify/demo/blob/main/src/plugins/custom/scrypt.ts) function:
> https://github.com/fastify/demo/blob/9455f5c2684403b70e209be6f1dfe48cb508c625/scripts/seed-database.ts#L51
> 
> 
> 

Yeah my bad, I didn't see that

**Comment by jean-michelet** [comment]
Thx @Mathieuka!
